
package live.chenchen.cxf2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2017-05-02T18:50:48.946+08:00
 * Generated source version: 2.3.3
 * 
 */
public final class MyServicePortType_MyServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://cxf2.chenchen.live/", "MyService");

    private MyServicePortType_MyServiceSoap_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MyService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MyService ss = new MyService(wsdlURL, SERVICE_NAME);
        MyServicePortType port = ss.getMyServiceSoap();  
        
		{
			System.out.println("Invoking getPersonById...");

			IdType idType = new IdType();
			idType.setId(1);

			PersonType personType = port.getPersonById(idType);

			System.out.println(personType.getAddress()
					+ ", "
					+ personType.getSchool().getSchoolName()
					+ ", "
					+ personType.getSchool().getRestaurant()
							.getRestaurantAddress());
		}

        System.exit(0);
    }

}
