
package live.chenchen.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2017-05-02T16:36:47.603+08:00
 * Generated source version: 2.3.3
 * 
 */
public final class MyService_MyServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://cxf2.chenchen.live/", "MyServiceImplService");

    private MyService_MyServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MyServiceImplService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MyServiceImplService ss = new MyServiceImplService(wsdlURL, SERVICE_NAME);
        MyService port = ss.getMyServiceImplPort();  
        
        {
        System.out.println("Invoking hello...");
        java.lang.String _hello_username = "zhangsan";
        java.lang.String _hello_password = "123456";
        java.lang.String _hello__return = port.hello(_hello_username, _hello_password);
        System.out.println("hello.result=" + _hello__return);


        }

        System.exit(0);
    }

}
